# Generated by Django 4.2 on 2023-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('ownerid', models.IntegerField(db_column='OwnerID', primary_key=True, serialize=False)),
                ('petowner', models.CharField(db_column='PetOwner', max_length=100)),
                ('petname', models.CharField(db_column='PetName', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=20)),
                ('address1', models.CharField(db_column='Address1', max_length=45)),
                ('address2', models.CharField(db_column='Address2', max_length=45)),
                ('city', models.CharField(db_column='City', max_length=45)),
                ('state', models.CharField(db_column='State', max_length=45)),
                ('zipcode', models.IntegerField(db_column='ZipCode')),
            ],
            options={
                'db_table': 'petownerpets',
                'managed': False,
            },
        ),
    ]
