# Generated by Django 4.2 on 2023-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('pet_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'patientaccounts',
                'managed': False,
            },
        ),
    ]
