# Generated by Django 4.2 on 2023-05-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petowners',
            fields=[
                ('petownerid', models.AutoField(db_column='PetOwnerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('address1', models.CharField(db_column='Address1', max_length=45)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=45, null=True)),
                ('city', models.CharField(db_column='City', max_length=45)),
                ('state', models.CharField(db_column='State', max_length=45)),
                ('zipcode', models.IntegerField(db_column='ZipCode')),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=20)),
                ('petid', models.IntegerField(db_column='PetID')),
            ],
            options={
                'db_table': 'petowners',
                'managed': False,
            },
        ),
    ]
