branch-defaults:
  master:
    environment: Capstone-dev
environment-defaults:
  Capstone-dev:
    branch: null
    repository: null
global:
  application_name: Capstone
  default_ec2_keyname: vetchart
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
