# Generated by Django 4.2 on 2023-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetLabs',
            fields=[
                ('petlabid', models.AutoField(db_column='PetlabID', primary_key=True, serialize=False)),
                ('petname', models.CharField(db_column='PetName', max_length=45)),
                ('wbc', models.IntegerField(db_column='WBC')),
                ('rbc', models.IntegerField(db_column='RBC')),
                ('hgb', models.IntegerField(db_column='HGB')),
                ('differential', models.IntegerField(db_column='Differential')),
                ('statusname', models.CharField(db_column='StatusName', max_length=45)),
            ],
            options={
                'db_table': 'patientpetlabs',
                'managed': False,
            },
        ),
    ]
