# Generated by Django 4.2 on 2023-05-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditems',
            fields=[
                ('itemid', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('description', models.CharField(db_column='Description', max_length=100)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=13, null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'fooditems',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
