# Generated by Django 4.2 on 2023-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescriptionid', models.AutoField(db_column='PrescriptionID', primary_key=True, serialize=False)),
                ('prescriptionname', models.CharField(db_column='PrescriptionName', max_length=45)),
                ('ownername', models.CharField(db_column='OwnerName', max_length=91)),
                ('petname', models.CharField(db_column='PetName', max_length=45)),
                ('status', models.IntegerField(db_column='Status')),
            ],
            options={
                'db_table': 'prescriptionlist',
                'managed': False,
            },
        ),
    ]
